var QuestionsAnswers = [
    {q: "Which is a chemical element?", answered: false, subcategory: "chemistry", round: "1", c1: "water", c2: "oil", c3: "alcohol", c4: "carbon", ans: "carbon"},
    {q: "Which is a molecule?", answered: false, subcategory: "chemistry", round: "1", c1: "water", c2: "carbon", c3: "lithium", c4: "potassium", ans: "water"},
    {q: "Which is a mixture?", answered: false, subcategory: "chemistry", round: "1", c1: "water", c2: "oil", c3: "sand", c4: "potassium", ans: "sand"},
    {q: "The higher the pKa of an acid the more...", answered: false, subcategory: "chemistry", round: "2", c1: "acidic", c2: "basic", c3: "slippery", c4: "rough", ans: "basic"},
    {q: "A buffer...", answered: false, subcategory: "chemistry", round: "2", c1: "makes a reaction proceed faster", c2: "slows down a reaction", c3: "encourages change in pH", c4: "resists change in pH", ans: "resists change in pH"},
    {q: "Which atom is the most electronegative?", answered: false, subcategory: "chemistry", round: "2", c1: "boron", c2: "xenon", c3: "oxygen", c4: "fluorine", ans: "fluorine"},
    {q: "What is the chemical name for the molecule CH4?", answered: false, subcategory: "chemistry", round: "3", c1: "methane", c2: "ethane", c3: "ethyne", c4: "dimethyl-ethyl", ans: "methane"},
    {q: "In nuclear equations a helium particle is referred to as a(n)...", answered: false, subcategory: "chemistry", round: "3", c1: "positron", c2: "gamma particle", c3: "beta particle", c4: "alpha particle", ans: "alpha particle"},
    {q: "A reaction that doesn't depend on concentration of the reactant is...", answered: false, subcategory: "chemistry", round: "3", c1: "zero order", c2: "first order", c3: "second order", c4: "none of the above", ans: "zero order"},
    {q: "What is the basic unit of life?", answered: false, subcategory: "biology", round: "1", c1: "protein", c2: "cell wall", c3: "cell", c4: "atom", ans: "cell"},
    {q: "Which organelle contains the genetic information?", answered: false, subcategory: "biology", round: "1", c1: "lysosome", c2: "nucleus", c3: "mitochondria", c4: "nucleolus", ans: "nucleus"},
    {q: "What is the structure of the cell membrane?", answered: false, subcategory: "biology", round: "1", c1: "phospholipid-bilayer", c2: "double-helix", c3: "hexagonal", c4: "trigonal-planar", ans: "phospholipid-bilayer"},
    {q: "Proteins are made from ___ acids", answered: false, subcategory: "biology", round: "2", c1: "carboxylic", c2: "amino", c3: "fatty", c4: "nucleic", ans: "amino"},
    {q: "This organelle acts as a recycling bin", answered: false, subcategory: "biology", round: "2", c1: "lysosome", c2: "ribosome", c3: "endoplasmic reticulum", c4: "mitochondria", ans: "lysosome"},
    {q: "What type of intermolecular bonds bind water molecules to one another?", answered: false, subcategory: "biology", round: "2", c1: "hydrogen", c2: "ionic", c3: "glycosidic", c4: "peptide", ans: "hydrogen"},
    {q: "How many cells are produced after meiosis 2?", answered: false, subcategory: "biology", round: "3", c1: "1", c2: "2", c3: "3", c4: "4", ans: "4"},
    {q: "When a G-protein binds guanosine-triphosphate it is considered...", answered: false, subcategory: "biology", round: "3", c1: "ineffective", c2: "active", c3: "inactive", c4: "effective", ans: "active"},
    {q: "This term refers to a plant's ability to bend in order to maximize light reception", answered: false, subcategory: "biology", round: "3", c1: "photoperiodism", c2: "photosynthesis", c3: "phototropism", c4: "photolysis", ans: "phototropism"},
    {q: "Assuming no air resistance- if dropped from same height which will hit the ground first?", answered: false, subcategory: "physics", round: "1", c1: "apple", c2: "elephant", c3: "car", c4: "none of the above", ans: "none of the above"},
    {q: "Force equals...", answered: false, subcategory: "physics", round: "1", c1: "ma", c2: "mc^2", c3: "1/2mv^2", c4: "v/t", ans: "ma"},
    {q: "Inertia is the...", answered: false, subcategory: "physics", round: "1", c1: "weight of object", c2: "momentum of object", c3: "resistance to movement", c4: "distance from Earth to moon", ans: "resistance to movement"},
    {q: "Assuming no air resistance- what's the final speed of an object dropped from 3 meters?", answered: false, subcategory: "physics", round: "2", c1: "6 m/s", c2: "0.6 m/s", c3: "0.8 m/s", c4: "8 m/s", ans: "8 m/s"},
    {q: "What height should an object fall from to accelerate for 3 seconds?", answered: false, subcategory: "physics", round: "2", c1: "90 m", c2: "40 m", c3: "9 m", c4: "none of the above", ans: "40 m"},
    {q: "How much time will it take for something to drop 18 meters from rest?", answered: false, subcategory: "physics", round: "2", c1: "36 s", c2: "3.7 s", c3: "1.9 s", c4: "none of the above", ans: "1.9 s"},
    {q: "Parallel resistors have equal...", answered: false, subcategory: "physics", round: "3", c1: "voltage", c2: "current", c3: "charge", c4: "none of the above", ans: "voltage"},
    {q: "What formula finds the specific gravity of a substance in water?", answered: false, subcategory: "physics", round: "3", c1: "mass/volume", c2: "(density of object)/(density of water)", c3: "mass*volume", c4: "none of the above", ans: "(density of object)/(density of water)"},
    {q: "In general as a substance heats up it...", answered: false, subcategory: "physics", round: "3", c1: "contracts", c2: "expands", c3: "freezes", c4: "none of the above", ans: "expands"},
    {q: "Which of the following is prime?", answered: false, subcategory: "mathematics", round: "1", c1: "2", c2: "4", c3: "9", c4: "12", ans: "2"},
    {q: "Which of the following is a rational number?", answered: false, subcategory: "mathematics", round: "1", c1: "pi", c2: "8/3", c3: "e", c4: "pi^2", ans: "8/3"},
    {q: "Which is an even number?", answered: false, subcategory: "mathematics", round: "1", c1: "1", c2: "5", c3: "7", c4: "10", ans: "10"},
    {q: "If 5x+9=4 find x", answered: false, subcategory: "mathematics", round: "2", c1: "25", c2: "-1", c3: "1", c4: "-25", ans: "-1"},
    {q: "log base 2 of 8 is...", answered: false, subcategory: "mathematics", round: "2", c1: "1", c2: "2", c3: "3", c4: "4", ans: "3"},
    {q: "What is the lowest common denominator of 1/6 and 1/9?", answered: false, subcategory: "mathematics", round: "2", c1: "6", c2: "9", c3: "3", c4: "18", ans: "18"},
    {q: "What is the radius of a circle with a circumference of 8pi units?", answered: false, subcategory: "mathematics", round: "3", c1: "8 units", c2: "4 units", c3: "3.14 units", c4: "2 units", ans: "4 units"},
    {q: "What is the radius of a circle with an area of 16pi units?", answered: false, subcategory: "mathematics", round: "3", c1: "8 units", c2: "4 units", c3: "3.14 units", c4: "2 units", ans: "4 units"},
    {q: "A secant line touches a circle at exactly __ point(s)", answered: false, subcategory: "mathematics", round: "3", c1: "1", c2: "2", c3: "3", c4: "4", ans: "2"},
    {q: "What year did Columbus discover America?", answered:false, subcategory: "history", round: "1", c1: "1492", c2: "1814", c3: "1499", c4: "0", ans: "1492"},
    {q: "What is the last name of the first president of the U.S.?", answered:false, subcategory: "history", round: "1", c1: "Adams", c2: "Jefferson", c3: "Washington", c4: "Lincoln", ans: "Washington"},
    {q: "What is national animal of the United States of America?", answered:false, subcategory: "history", round: "1", c1: "Zebra", c2: "Elephant", c3: "Donkey", c4: "Eagle", ans: "Eagle"},
    {q: "How many colonies did New England have?", answered:false, subcategory: "history", round: "2", c1: "10", c2: "11", c3: "12", c4: "13", ans: "13"},
    {q: "Who was the 16th President of the U.S.?", answered:false, subcategory: "history", round: "2", c1: "Lincoln", c2: "Adams", c3: "Bush", c4: "Washington", ans: "Lincoln"},
    {q: "What year was the Declaration of Independence written?", answered:false, subcategory: "history", round: "2", c1: "1302", c2: "1776", c3: "1434", c4: "1800", ans: "1776"},
    {q: "What is the highest American value?", answered:false, subcategory: "history", round: "3", c1: "Freedom", c2: "Money", c3: "Domination", c4: "Pleasure", ans: "Freedom"},
    {q: "Who discovered America?", answered:false, subcategory: "history", round: "3", c1: "Columbus", c2: "Galileo", c3: "Marco Polo", c4: "None of the above", ans: "Columbus"},
    {q: "What government branch is the president associated with?", answered:false, subcategory: "history", round: "3", c1: "Legislative", c2: "Executive", c3: "Judicial", c4: "None", ans: "Executive"},
    // {q: "What is the speed of light?", answered:false, subcategory: "physics", round: "1", c1: "3x10^8 m/s^2", c2: "9.8 m/s^2", c3: "-9.8 m/s^2", c4: "-3x10^8 m/s^2", ans: "3x10^8 m/s^2"},
    // {q: "Who discovered the speed of light?", answered:false, subcategory: "physics", round: "1", c1: "Albert Einstein", c2: "James Clark Maxwell", c3: "Erwin Schrodinger", c4: "Isaac Newton", ans: "Albert Einstein"},
    // {q: "A dog runs from one side of a park to the other. The park is 80.0 meters across. The dog takes 16.0 seconds to cross the park. What is the speed of the dog?", answered:false, subcategory: "physics", round: "1", c1: "5 m/s", c2: "10 m/s", c3: "4 m/s", c4: "8 m/s", ans: "5 m/s"},
    // {q: "A golf cart is driven at its top speed of 27.0 km/h for 10.0 minutes. In meters, how far did the golf cart travel?", answered:false, subcategory: "physics", round: "1", c1: "4500 m", c2: "450 km", c3: "45 km", c4: "450 m", ans: "4500 m"},
    // {q: "Given acceleration can you find velocity? a(t) = 10t + 5", answered:false, subcategory: "physics", round: "2", c1: "v(t)=10t+5", c2: "v(t)=5t^2+5t+c", c3: "10", c4: "5", ans: "v(t)=5t^2+5t+c"},
    // {q: "Given velocity can you find acceleration? a(t) = 5t^2 + 5t", answered:false, subcategory: "physics", round: "2", c1: "a(t)=10t+5", c2: "a(t)=5t^2+5t+c", c3: "10", c4: "5", ans: "a(t)=10t+5"},
    // {q: "Find the current of an electrical circuit that has resistance of 50 Ohms and voltage supply of 5 Volts.", answered:false, subcategory: "physics", round: "2", c1: "0.1 A", c2: "1.0 A", c3: "0.01 A", c4: "10.0 A", ans: "0.1 A"},
    // {q: "Find the resistance of an electrical circuit that has voltage supply of 10 Volts and current of 5mA.", answered:false, subcategory: "physics", round: "3", c1: "2000 Ohms", c2: "200 Ohms", c3: "2000 kOhms", c4: "200 kOhms", ans: "2000 Ohms"},
    // {q: "Schrodinger equations helps describe what type of functions?", answered:false, subcategory: "physics", round: "3", c1: "wave", c2: "particle", c3: "voltage", c4: "quantum", ans: "wave"},
    // {q: "What animal became famous from Schrodinger?", answered:false, subcategory: "physics", round: "3", c1: "Dog", c2: "Hamster", c3: "Monkey", c4: "Cat", ans: "Cat"},
]; 
module.exports = QuestionsAnswers;